// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPkH1FJ0HDWSn0CvMelJpB7j7nWWTnctU',
    appId: '1:963076663974:web:b468c7e0a6669e19dca267',
    messagingSenderId: '963076663974',
    projectId: 'family-hosehold-management-pro',
    authDomain: 'family-hosehold-management-pro.firebaseapp.com',
    storageBucket: 'family-hosehold-management-pro.firebasestorage.app',
    measurementId: 'G-B8RQLGZN6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3CbdqSF-3V4HanAQ5R2lfrdM-kNl0mi4',
    appId: '1:963076663974:android:f7cadcad1cfa750bdca267',
    messagingSenderId: '963076663974',
    projectId: 'family-hosehold-management-pro',
    storageBucket: 'family-hosehold-management-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOaEjlqyWBysYpraIXH2UgT3FqTsoUFpw',
    appId: '1:963076663974:ios:e86d6dd008de51d9dca267',
    messagingSenderId: '963076663974',
    projectId: 'family-hosehold-management-pro',
    storageBucket: 'family-hosehold-management-pro.firebasestorage.app',
    iosClientId: '963076663974-n13qu4ru9b5p2ko052q8ip00htt73mao.apps.googleusercontent.com',
    iosBundleId: 'com.example.notSoTicTacToe',
  );
}
